export const INITIAL_DATA = "INITIAL_DATA";

export const AUTHED_USER = "AUTHED_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const INITIAL_QUESTIONS = "INITIAL_QUESTIONS";
export const ADD_USER_ID_IN_QUESTION = "ADD_USER_ID_IN_QUESTION";
export const ADD_QUESTION = "ADD_QUESTION";

export const INITIAL_USERS = "INITIAL_USERS";
export const ADD_ANSWER_IN_QUESTION = "ADD_ANSWER_IN_QUESTION";
export const ADD_QUESTION_IN_USER = "ADD_QUESTION_IN_USER";

export const REGISTER_USER = "REGISTER_USER";
